# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/will/redpitaya/fpga_examples/redpitaya_guide/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
# IP: The module: 'system_util_ds_buf_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/will/redpitaya/fpga_examples/redpitaya_guide/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_2_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/will/redpitaya/fpga_examples/redpitaya_guide/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0.xci
# IP: The module: 'system_util_ds_buf_2_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/will/redpitaya/fpga_examples/redpitaya_guide/tmp/1_led_blink/1_led_blink.srcs/sources_1/bd/system/ip/system_util_ds_buf_2_0/system_util_ds_buf_2_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_util_ds_buf_2_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
